apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
      - name: workflow-controller
        image: jessesuen/workflow-controller:v2.2-preview
        imagePullPolicy: Always
        command:
        - workflow-controller
        args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - jessesuen/argoexec:v2.2-preview
